### ISSUE TITLE
VueJS use-cases

### ISSUE THREAD

**Issue by adamk22** [suomato/base-camp#11]
Maybe it's me being a bit of a traditional WP developer. But what are the use-cases and best practices for using vuejs? How would you go about implementing it during theme building? I couldn't find anything about in the docs other than a bit of example code the main.js file. 

Other than that, I'm very happy to have found this! I've checked out Sage 9, Tonik and lots of other starter themes, but base-camp is the best one so far!

**Comment by suomato** [comment]
Hi @adamk22 

I'm very happy to hear that you liked Base Camp. That's true, there are no examples how to use Vuejs components in a theme. Only bit of boilerplate how to make a Vuejs component. Maybe I should make a small real-life component and show how to use it in the theme.    

One of the Vuejs use-cases would be that you use WordPress only as a REST API and build the frontend using Vuejs. Base Camp uses [bulma](https://bulma.io/) which contains many good-looking components without JavaScript logic. Vuejs is the perfect match with that library to bring those components alive.

**Comment by adamk22** [comment]
Thanks for answering! That was one of the use-cases that crossed my mind. I thought it was added for using it as some kind of substitute for jQuery or js animations/handling or something. But the idea of including is to have the option to ditch Twig for vuejs?

**Comment by suomato** [comment]
There are some options what you can do with Vuejs:
* using it instead of jQuery (animation, API calls, etc.)
* replace Twig with Vuejs components
* adding an interactive component in twig template
* etc.

There are many cool component libraries made for Vuejs e.g. [Element](http://element.eleme.io/#/en-US/component/installation) that you can use very easily in your own theme thanks to the implemented Vuejs.

Of course all of these cases are fully optional. It's not necessary to use Vuejs at all if you don't want to. However, by replacing Twig completely with Vuejs will cause a lot of extra work for you because then you have to rewrite the existing frontend again.

**Comment by suomato** [comment]
@adamk22 Did you get a satisfying answer?

**Comment by ewarrin** [comment]
Im wanting to use Vue to do some animations but I can't figure out how to get the component inside my twig view. Any quick direction on this without you having to create a whole example?

**Comment by suomato** [comment]
Follow these three steps:
1. Make Single File Components (like Example.vue)
2. Add component to Vue instance in `resources/assets/js/main.js` like this:
```
import YourComponent from './components/YourComponent';

new Vue({
  el: '#app',
  components: {
    YourComponent,
  },
});
``` 
3. Now you are able to use your component anywhere on your page because Vue instance scope is `#app` and entire page is wrapped inside `<div id="app"></div>` . 

NOTE: In twig file you should use kebab-case to define Vue components like this: 
```
<your-component></your-component>
```

**Comment by ewarrin** [comment]
Awesome thanks so much. I wasn't using kebab-case.
